@host=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvc21pbkBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJ0ZXN0IiwibGFzdE5hbWUiOiJ0ZXN0IGxhc3QgbmFtZSIsImFnZSI6MzUsImlhdCI6MTUzNDE3MjA0MX0.PHwqlhSo0qTz6x9pyI-mlLaPSyOxxb-6fwOF7kpLDeI

## Users API

### Get all users
GET {{host}}/users
content-type: application/json

### Create new user

POST {{host}}/users
content-type: application/json

{
    "firstName": "test",
    "lastName": "test last name",
    "age": 35,
    "email": "test1243@gmail.com",
    "password": "21341"
}

## Campaigns API

### Get all campagins

GET {{host}}/campaigns

### register user

POST {{host}}/register
content-type: application/json

{
    "firstName": "test",
    "lastName": "test last name",
    "email": "test@test.com",
    "password": "123456"
}

### login user

POST {{host}}/login
content-type: application/json

{
    "email": "cossadsamin@gmsadsadail.com",
    "password": "123456"
}

### get user 

get {{host}}/users/me
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCfJ9.eyJmaXJzdE5hbWUiOiJDb3NtaW4iLCJsYXN0TmFtZSI6IklvbmFzY3UiLCJhZ2UiOjMwLCJlbWFpbCI6InRlc3RAdGVzdDIuY29tIiwiaWQiOjIxLCJpYXQiOjE1MzQ4MzkxMjR9.z9eIgtJY5VB8bTull6loX1DWqfG7i10B-whEQ2jfoI0


### auth with facebook

POST {{host}}/auth/provider
content-type: application/json

{
    "provider": "facebook",
    "authToken": "EAACyu34bczdddwBAIOqXSCWW4w1ity8YD85nlcRfPEbK1WYVc8SXT2mSjyG4JG95fgJ2xKj6R69XX3ipO04yRvu7O79n3o0snKRvsIHkC8l8tNpHaezS02E9ZAc6ZA2fNEg77Moy3XqBslH9ZB0q3YbBLM3zzHanbaQb9qZA4mFSKpehuzfNw0UfyxyjnJppSJQeQYqcLt9fSmbR1SCS4qd"
}