@host=http://localhost:3000

## Users API

### Get all users
GET {{host}}/users
content-type: application/json

### Create new user

POST {{host}}/users
content-type: application/json

{
    "firstName": "test",
    "lastName": "test last name",
    "age": 35
}

## Campaigns API

### Get all campagins

GET {{host}}/campaigns

### register user

POST {{host}}/register
content-type: application/json

{
    "firstName": "test",
    "lastName": "test last name",
    "age": 35,
    "email": "cosmin@gmail.com",
    "password": "123"
}

### login user

POST {{host}}/login
content-type: application/json

{
    "email": "*",
    "password": "123"
}