@host=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvc21pbkBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJ0ZXN0IiwibGFzdE5hbWUiOiJ0ZXN0IGxhc3QgbmFtZSIsImFnZSI6MzUsImlhdCI6MTUzNDE3MjA0MX0.PHwqlhSo0qTz6x9pyI-mlLaPSyOxxb-6fwOF7kpLDeI

## Users API

### Get all users
GET {{host}}/users
content-type: application/json

### Create new user

POST {{host}}/users
content-type: application/json

{
    "firstName": "test",
    "lastName": "test last name",
    "age": 35,
    "email": "test1243@gmail.com",
    "password": "21341"
}

## Campaigns API

### Get all campagins

GET {{host}}/campaigns

### register user

POST {{host}}/register
content-type: application/json

{
    "firstName": "test",
    "lastName": "test last name",
    "email": "test@test.com",
    "password": "123456"
}

### login user

POST {{host}}/auth/local
content-type: application/json

{
    "email": "test@test1.com",
    "password": "123456"
}

### get user 

get {{host}}/users/me
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsImZpcnN0TmFtZSI6IkNvc21pbiIsImVtYWlsIjoidGVzdEB0ZXN0MS5jb20iLCJsYXN0TmFtZSI6IklvbmFzY3UiLCJhZ2UiOjMwLCJpYXQiOjE1MzUwMjU0NjZ9.18OMqv2rZniF3inGrPiuzIvGXl6LvDxcjnhJJj1pq-c

### auth with facebook

POST {{host}}/auth/provider
content-type: application/json

{
    "provider": "facebook",
    "authToken": "EAACyu34bczwBAHxRq5M33L1WYZAUwl7LN7lP96VMSGEiuYkZAFSIcMuBdZCmXZCjnDP8WypIlEu0NybegcgK0UxXXvHdAZBDovzbJiZCZBHvwNedNJ3KbSNc2mdTmfYYyuLcJt2ufOLZCTIL19Q3vSTBUtvN5SChFm0BMLWYxiquD2vNDwpV2RwEEG9th7ECrGexxCTytjDDqLZCFnkz3EEgH"
}


### get user 

get https://graph.facebook.com/me?access_token=EAACyu34bczwBAHxRq5M33L1WYZAUwl7LN7lP96VMSGEiuYkZAFSIcMuBdZCmXZCjnDP8WypIlEu0NybegcgK0UxXXvHdAZBDovzbJiZCZBHvwNedNJ3KbSNc2mdTmfYYyuLcJt2ufOLZCTIL19Q3vSTBUtvN5SChFm0BMLWYxiquD2vNDwpV2RwEEG9th7ECrGexxCTytjDDqLZCFnkz3EEgH
content-type: application/json


